### ISSUE TITLE
Elbox PCI not more working

### ISSUE THREAD

**Issue by mds1964** [michalsc/Emu68#233]
Hi,
Just try to install pistormlite on Amiga1200 eith elbox tower and pci bosrd.
The last working core was 0.15.3 from11.07.2023.
On lster builds, only the 68 Pistorm screen is visible.
No booting into Workbench.
Any Idea?

**Comment by autmarder** [comment]
Hello,
is your problem solved in the meantime?

**Comment by Hakke1** [comment]
I am confirming the crashes of basically all Mediator PCI devices with Pistorm versions newer than 0.15.3 from11.07.2023. Adjusting any Pistorm parameters via Emu68control does not solve the problem. Very annoying having to restart every few minutes. 

I hope this issue can be resolved soon. Going back to the older versions is not really an option with my Pi4.

**Comment by JustOneGarnetto** [comment]
I also have these issues with a Mediator 1200TX. If I try to use RTG on my Radeon the display is always corrupted and the machine freezes. Ethernet works initially but then stops working, usually freezing the OS but not every time. Sometimes I can just reconnect and it will work again for a short while. I have to admit I've had no issues so far with my sound card.

I am using the latest version of the pci.library (v13.15). I have used the pistorm with both a pi 3b+ and pi and the issues are present with both.

**Comment by Tijnzie** [comment]
Anywhere i can find Emu68-pistorm32lite-20230310-f9cd01.zip ?
I've been checking Discord occasionally to see if there is an update for emu68 that fixes the mediator issues (I've not played around with RTG a lot, but I sure have the ethernet issues). However I can't seem to find Emu68-pistorm32lite-20230310-f9cd01.zip anymore (too old nightly?)

**Comment by michalsc** [comment]
Guys, can you please test the most recent release and report back? It is hard to know if the issue is fixed or not when there is no feedback...

**Comment by captain-amygdala** [comment]
Also please open a additional issue on the PiStorm32lite GitHub if possible. Michal and I work close together, but I don't monitor Michals GitHub or get notifications :) https://github.com/PiStorm/pistorm32-lite-gateware

**Comment by Hakke1** [comment]
I have tested the latest Emu68 1.0.5.1 on my Amiga 1200 with Mediator 1200TX. Unfortunately the same issues remain as mentioned above. I have even used the standard config.txt file, which at first gave some promising stability as it does not overclock the Pi. But after some further testing, the same issues appeared again... "Ethernet works initially but then stops working," "The USB crashes, The ethernet crashes. Even the SoundBlaster ..."

**Comment by MicroXs** [comment]
I have tested the latest Emu68 1.0.6 on my Amiga 1200 with Mediator 1200TX & PI4. My USB key does not crash. My Soundblaster works fine. My ethetnet card used to crash after 3 mins, not anymore. My Voodoo card was working fine before, but I don't use it anymore.

My config.txt:

kernel=Emu68-pistorm32lite
disable_splash=1
arm_64bit=1

total_mem=2048

boot_delay=1

avoid_warnings=1

hdmi_force_hotplug=1

gpu_mem=256
hdmi_group=2
hdmi_mode=82

initramfs kick321.ROM

**Comment by Hakke1** [comment]
I as well just tested Emu68 version 1.0.6 on my Amiga 1200 with Mediator 1200TX & PI4. It's still not working.
After some initial hope (at least with disabled arm_boost), the PCI board still froze when trying to transfer some larger files via wired Ethernet. So it's back to version 0.15.3 again.

**Comment by captain-amygdala** [comment]
@michalsc , I suggest to close the issue. @mds1964 reported his system works now, also other reports that with the mediator fixed FPGA firmware their mediator setup is working. I will push the changes to the pistorm32lite-gateware repository as I didn't received reports that the mediator fixed firmware (included in emu68 since 1.0.5) introduced different behaviour in non-mediator systems. So I consider the fix as stable

**Comment by Hakke1** [comment]
I just tried the latest version 1.0.6 again. I even used the uneditted config file, no overclocking or ARM boost. While it looks a bit more stable, my Ethernet still freezes after a while. I downloaded a 60MB file from Aminet, but it froze at about 30MB.
Still, version 0.15.3 does not freeze.

**Comment by michalsc** [comment]
Closing the issue following suggestion from @captain-amygdala - cannot verify and cannot reproduce the issue due to lack of hardware.
